
create table person(
    id char(18),
	name varchar(20)
)
go

--校验函数
CREATE FUNCTION dbo.VerifyID(@ID char(18))
RETURNS INT
AS
BEGIN
   DECLARE @ANS1 INT
   DECLARE @ANS INT
   DECLARE @RE INT
   SELECT @ANS1 = 7*CAST(SUBSTRING(@ID,1,1) AS INT)+ 9*CAST(SUBSTRING(@ID,2,1) AS INT) + 10*CAST(SUBSTRING(@ID,3,1) AS INT) +5*CAST(SUBSTRING(@ID,4,1) AS INT)
               + 8*CAST(SUBSTRING(@ID,5,1) AS INT)+ 4*CAST(SUBSTRING(@ID,6,1) AS INT)+ 2*CAST(SUBSTRING(@ID,7,1) AS INT)+ 1*CAST(SUBSTRING(@ID,8,1) AS INT)
			    +6*CAST(SUBSTRING(@ID,9,1) AS INT) +3*CAST(SUBSTRING(@ID,10,1) AS INT) +7*CAST(SUBSTRING(@ID,11,1) AS INT) +9*CAST(SUBSTRING(@ID,12,1) AS INT) 
				+10*CAST(SUBSTRING(@ID,13,1) AS INT) +5*CAST(SUBSTRING(@ID,14,1) AS INT) +8*CAST(SUBSTRING(@ID,15,1) AS INT) +4*CAST(SUBSTRING(@ID,16,1) AS INT) 
				+2*CAST(SUBSTRING(@ID,17,1) AS INT)
   SELECT @ANS = @ANS1 % 11
   IF @ANS = CAST(SUBSTRING(@ID,18,1) AS INT)
      SELECT @RE = 0
   ELSE
      SELECT @RE = 1
   RETURN @RE   
END
go

--添加约束条件
alter table person
add constraint ID_Verify check (dbo.Verify_ID(id)=0)